# Generated by Django 4.1.5 on 2023-02-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0004_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
