# Generated by Django 4.1.5 on 2023-02-04 08:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StoreApp', '0005_alter_review_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='descriptions',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
