# Generated by Django 4.1.5 on 2023-02-28 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'SMS Log',
                'verbose_name_plural': 'SMS Logs',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SMSToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('token', models.TextField()),
                ('expires_at', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'SMS Token',
                'verbose_name_plural': 'SMS Tokens',
                'ordering': ['-id'],
            },
        ),
    ]
