# Generated by Django 3.2.16 on 2023-03-01 08:05

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('order', '0004_auto_20230301_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='regions', chained_model_field='regions', null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.city'),
        ),
        migrations.AddField(
            model_name='order',
            name='regions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.region'),
        ),
    ]
