# Generated by Django 3.2.16 on 2023-02-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20230211_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_id_pk',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
