# Generated by Django 3.2.16 on 2023-02-20 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20230219_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id_pk',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
