# Generated by Django 3.2.16 on 2023-01-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basemodel',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='basemodel',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
