# Generated by Django 3.2.16 on 2023-01-29 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20230129_1210'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaseModel',
        ),
    ]
