# Generated by Django 4.1.5 on 2023-02-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default=1, max_length=60, unique=True),
            preserve_default=False,
        ),
    ]
