# Generated by Django 4.1.5 on 2023-02-19 09:10

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0002_cartitems_status'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cartitems',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
