# Generated by Django 4.1.5 on 2023-02-19 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0003_alter_cartitems_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cartitems',
            managers=[
            ],
        ),
    ]
