# Generated by Django 3.2.16 on 2023-01-29 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_image_product_product_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_images',
            new_name='image',
        ),
    ]
