# Generated by Django 3.2.16 on 2023-02-09 15:11

from django.db import migrations, models
import src.apps.store.models.review


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20230209_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='desc',
            field=models.TextField(help_text='Review haqida izoh', validators=[src.apps.store.models.review.validate_desc]),
        ),
        migrations.DeleteModel(
            name='ProductVariants',
        ),
    ]
